kind: pipeline
type: docker
name: default

clone:
  disable: true

steps:
  - name: clone
    image: alpine/git
    commands:
        - git clone ssh://git@gitea:22/ben/dashy.git .
    network_mode: vm-dev-net

  - name: test
    image: python:3.12-slim
    commands:
      - pip install -r requirements.txt
      - pytest
    network_mode: vm-dev-net