kind: pipeline
type: docker
name: default

clone:
  disable: true

steps:
  - name: test
    image: python:3.12-slim
    commands:
      - pip install -r requirements.txt
      - pytest
    network_mode: vm-dev-net